// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(PansRoomContext))]
    [Migration("20210405232129_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("Models.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlreadyInCollection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("Models.Collection", b =>
                {
                    b.HasOne("Models.Disc", "Disc")
                        .WithMany()
                        .HasForeignKey("DiscId")
                        .HasConstraintName("FK__Collectio__DiscI__2E1BDC42")
                        .IsRequired();

                    b.Navigation("Disc");
                });

            modelBuilder.Entity("Models.Disc", b =>
                {
                    b.HasOne("Models.Artist", "Artist")
                        .WithMany("Discs")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("FK__Discs__ArtistId__2C3393D0")
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Models.WishList", b =>
                {
                    b.HasOne("Models.Disc", "Disc")
                        .WithMany()
                        .HasForeignKey("DiscId")
                        .HasConstraintName("FK__WishList__DiscId__2D27B809")
                        .IsRequired();

                    b.Navigation("Disc");
                });

            modelBuilder.Entity("Models.Artist", b =>
                {
                    b.Navigation("Discs");
                });
#pragma warning restore 612, 618
        }
    }
}
